# Generated by Django 5.1 on 2024-08-12 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_savedpassword"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.RemoveField(
            model_name="user",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
